### PR TITLE
Update highscore.hbs

### PR DESCRIPTION
**Pull request by Triomat**

### CODE REVIEW

**Comment by syxolk** [comment]
Hey, if you want a German version we could integrate an internationalization module.

**Comment by Triomat** [comment]
Hi syxolk,
i am completly new to GitHub so excuse my Pull Request (And further strange moves).
Because of that I also don't know what you mean with the internationalization module?

**Comment by syxolk** [comment]
Currently all strings like `'Score'` are directly embedded in the HTML templates.

What I want to do instead is something like this: `getMessage('score')` which returns either `'Score'` or `'Punkte'` depending on the user's settings.

**Comment by Triomat** [comment]
Well this would be beautiful to see. 
I want to use your betting game for my friends. And English is not mastered by everyone of them :)

**Pull request closed without merging**
